<?php

register_post_type('careers', array(
    'name' => 'careers',
    'label' => 'Careers',
    'active' => true,
    'description' => 'Add a job posting!',
    'hierarchical' => false,
    'supports' => array(
        'title',
        'editor',
        'thumbnail',
        'excerpt',
        'custom-fields',
        'revisions',
        'page-attributes',
    ),
    'taxonomies' => array(
        'category',
        'post_tag',
        'post_format',
    ),
    'public' => true,
    'exclude_from_search' => false,
    'publicly_queryable' => true,
    'can_export' => true,
    'delete_with_user' => false,
    'labels' => array(
        'singular_name' => 'career',
        'add_new' => 'add new Job Posting',
        'add_new_item' => 'add a new Job Posting',
        'edit_item' => 'edit Job Posting',
        'new_item' => 'new Job Posting',
        'view_item' => 'Job Posting',
        'view_items' => 'View Job Postings and Careers',
        'search_items' => 'Search Careers',
        'item_updated' => 'Job posting updated',
    ),
    'menu_position' => 4,
    'menu_icon' => 'dashicons-businesswoman',
    'show_ui' => false,
    'show_in_menu' => false,
    'show_in_nav_menus' => false,
    'show_in_admin_bar' => false,
    'has_archive' => false,
    'rewrite' => true,
    'capability_type' => 'post',
    'capabilities' => array(),
    'map_meta_cap' => null,
    'show_in_rest' => true,
    'rest_base' => '',
    'rest_controller_class' => 'WP_REST_Posts_Controller',
    'acfe_archive_template' => '',
    'acfe_archive_ppp' => 10,
    'acfe_archive_orderby' => 'date',
    'acfe_archive_order' => 'DESC',
    'acfe_archive_meta_key' => '',
    'acfe_archive_meta_type' => '',
    'acfe_single_template' => 'career-single.php',
    'acfe_admin_archive' => false,
    'acfe_admin_ppp' => 10,
    'acfe_admin_orderby' => 'date',
    'acfe_admin_order' => 'DESC',
    'acfe_admin_meta_key' => '',
    'acfe_admin_meta_type' => '',
));

register_post_type('case-studies', array(
    'name' => 'case-studies',
    'label' => 'Case Studies',
    'active' => true,
    'description' => '',
    'hierarchical' => true,
    'supports' => array(
        'title',
        'editor',
        'author',
        'thumbnail',
        'custom-fields',
        'revisions',
    ),
    'taxonomies' => array(
        'category',
        'specialties',
    ),
    'public' => true,
    'exclude_from_search' => false,
    'publicly_queryable' => true,
    'can_export' => true,
    'delete_with_user' => false,
    'labels' => array(
        'singular_name' => 'Case Study',
        'add_new_item' => 'Add new Case Study',
        'edit_item' => 'Edit Case Study',
        'new_item' => 'New Case Study',
        'view_item' => 'View Case Study',
        'view_items' => 'View Case Studies',
        'search_items' => 'Search Case Studies',
        'all_items' => 'All Case Studies',
    ),
    'menu_position' => 2,
    'menu_icon' => 'dashicons-images-alt',
    'show_ui' => true,
    'show_in_menu' => true,
    'show_in_nav_menus' => true,
    'show_in_admin_bar' => true,
    'has_archive' => false,
    'rewrite' => array(
        'slug' => 'work',
        'with_front' => false,
        'feeds' => false,
        'pages' => true,
    ),
    'capability_type' => 'post',
    'capabilities' => array(),
    'map_meta_cap' => null,
    'show_in_rest' => true,
    'rest_base' => '',
    'rest_controller_class' => 'WP_REST_Posts_Controller',
    'acfe_archive_template' => '',
    'acfe_archive_ppp' => 10,
    'acfe_archive_orderby' => 'date',
    'acfe_archive_order' => 'DESC',
    'acfe_archive_meta_key' => '',
    'acfe_archive_meta_type' => '',
    'acfe_single_template' => 'case-study.php',
    'acfe_admin_archive' => false,
    'acfe_admin_ppp' => 10,
    'acfe_admin_orderby' => 'date',
    'acfe_admin_order' => 'DESC',
    'acfe_admin_meta_key' => '',
    'acfe_admin_meta_type' => '',
));

register_post_type('external-link', array(
    'name' => 'external-link',
    'label' => 'External link',
    'active' => true,
    'description' => 'Add a external link as a page to workwithsupdev.wpengine.com',
    'hierarchical' => true,
    'supports' => array(
        'title',
        'author',
        'thumbnail',
        'custom-fields',
        'page-attributes',
    ),
    'taxonomies' => array(
        'category',
        'post_tag',
        'post_format',
    ),
    'public' => true,
    'exclude_from_search' => false,
    'publicly_queryable' => true,
    'can_export' => true,
    'delete_with_user' => false,
    'labels' => array(
        'singular_name' => 'External link',
        'add_new' => 'link',
    ),
    'menu_position' => 4,
    'menu_icon' => 'dashicons-exit',
    'show_ui' => true,
    'show_in_menu' => true,
    'show_in_nav_menus' => true,
    'show_in_admin_bar' => true,
    'has_archive' => true,
    'rewrite' => true,
    'capability_type' => 'post',
    'capabilities' => array(),
    'map_meta_cap' => null,
    'show_in_rest' => true,
    'rest_base' => '',
    'rest_controller_class' => 'WP_REST_Posts_Controller',
    'acfe_archive_template' => '',
    'acfe_archive_ppp' => 10,
    'acfe_archive_orderby' => 'date',
    'acfe_archive_order' => 'DESC',
    'acfe_archive_meta_key' => '',
    'acfe_archive_meta_type' => '',
    'acfe_single_template' => 'external-link.php',
    'acfe_admin_archive' => false,
    'acfe_admin_ppp' => 10,
    'acfe_admin_orderby' => 'date',
    'acfe_admin_order' => 'DESC',
    'acfe_admin_meta_key' => '',
    'acfe_admin_meta_type' => '',
));

register_post_type('service-offerings', array(
    'name' => 'service-offerings',
    'label' => 'Service Offerings',
    'active' => true,
    'description' => '',
    'hierarchical' => false,
    'supports' => array(
        'title',
        'editor',
        'thumbnail',
        'revisions',
        'page-attributes',
    ),
    'taxonomies' => array(
        'category',
        'post_tag',
        'post_format',
        'specialties',
    ),
    'public' => true,
    'exclude_from_search' => false,
    'publicly_queryable' => true,
    'can_export' => true,
    'delete_with_user' => false,
    'labels' => array(
        'singular_name' => 'Service Offering',
        'add_new' => 'Add New Offering',
        'add_new_item' => 'Add New Service Offering',
        'edit_item' => 'Edit Offering',
        'new_item' => 'New Offering',
        'view_item' => 'View Service Offering',
        'view_items' => 'View Service Offerings',
        'search_items' => 'Search Service Offerings',
        'all_items' => 'All Service Offerings',
    ),
    'menu_position' => '',
    'menu_icon' => 'dashicons-format-aside',
    'show_ui' => true,
    'show_in_menu' => true,
    'show_in_nav_menus' => true,
    'show_in_admin_bar' => true,
    'has_archive' => false,
    'rewrite' => array(
        'slug' => 'services',
        'with_front' => false,
        'feeds' => false,
        'pages' => true,
    ),
    'capability_type' => 'post',
    'capabilities' => array(),
    'map_meta_cap' => null,
    'show_in_rest' => true,
    'rest_base' => '',
    'rest_controller_class' => 'WP_REST_Posts_Controller',
    'acfe_archive_template' => '',
    'acfe_archive_ppp' => 10,
    'acfe_archive_orderby' => 'date',
    'acfe_archive_order' => 'DESC',
    'acfe_archive_meta_key' => '',
    'acfe_archive_meta_type' => '',
    'acfe_single_template' => 'offerings.php',
    'acfe_admin_archive' => false,
    'acfe_admin_ppp' => 10,
    'acfe_admin_orderby' => 'date',
    'acfe_admin_order' => 'DESC',
    'acfe_admin_meta_key' => '',
    'acfe_admin_meta_type' => '',
));

